version: "3"

services:
  rabbitmq:
    image: rabbitmq:3.12-rc-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 1883:1883
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./definitions.json:/etc/rabbitmq/definitions.json
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 30s
      retries: 30
  app:
    build: .
    container_name: app
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOSTNAME=rabbitmq